// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PFMBusinessLogic.Database;

#nullable disable

namespace PFMBusinessLogic.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221219175223_MoviesDB")]
    partial class MoviesDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoviePerson", b =>
                {
                    b.Property<string>("ActorsName")
                        .HasColumnType("text");

                    b.Property<string>("MoviesTitle")
                        .HasColumnType("text");

                    b.HasKey("ActorsName", "MoviesTitle");

                    b.HasIndex("MoviesTitle");

                    b.ToTable("MoviePerson");
                });

            modelBuilder.Entity("MovieTag", b =>
                {
                    b.Property<string>("MoviesTitle")
                        .HasColumnType("text");

                    b.Property<string>("TagsName")
                        .HasColumnType("text");

                    b.HasKey("MoviesTitle", "TagsName");

                    b.HasIndex("TagsName");

                    b.ToTable("MovieTag");
                });

            modelBuilder.Entity("PFMBusinessLogic.Models.Movie", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("DirectorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovieTitle")
                        .HasColumnType("text");

                    b.Property<string>("Rate")
                        .HasColumnType("text");

                    b.HasKey("Title");

                    b.HasIndex("DirectorName");

                    b.HasIndex("MovieTitle");

                    b.ToTable("MoviesStorage");
                });

            modelBuilder.Entity("PFMBusinessLogic.Models.Person", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("PersonsStorage");
                });

            modelBuilder.Entity("PFMBusinessLogic.Models.Tag", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("TagsStorage");
                });

            modelBuilder.Entity("MoviePerson", b =>
                {
                    b.HasOne("PFMBusinessLogic.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("ActorsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFMBusinessLogic.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTag", b =>
                {
                    b.HasOne("PFMBusinessLogic.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFMBusinessLogic.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PFMBusinessLogic.Models.Movie", b =>
                {
                    b.HasOne("PFMBusinessLogic.Models.Person", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFMBusinessLogic.Models.Movie", null)
                        .WithMany("Top10Related")
                        .HasForeignKey("MovieTitle");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("PFMBusinessLogic.Models.Movie", b =>
                {
                    b.Navigation("Top10Related");
                });
#pragma warning restore 612, 618
        }
    }
}
